### ISSUE TITLE
Regulator Mode thoughts

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorageaddons#43]
Post your ideas here.

**Comment by tgstyle** [comment]
Could it be an addon that adds an upgrade card to put in the exporter? Or will it need to be a whole new device?

**Comment by Enverex** [comment]
Or alternatively it being a separate item to the exporter entirely simply called an "Export Regulator" or something, that way it could have a proper GUI for setting the amount to export at once, quantity to keep in the target storage, etc.

**Comment by Paril** [comment]
Regulator Mode would make this the only mod (to my knowledge) that does this sort of inventory management whilst being able to keep things in stock all in one, so it'd be super amazing to have this back in.

Bonus points if it works in Fluid Mode, allowing for precise mixing of fluids in, say, the Tinkers' Smeltery.

I don't like the idea of using Upgrades because of how limited they can be when mixed; for instance, using a Stack Upgrade then limits you to only 3 speed upgrades. With regulator you'd be limiting yourself even further.

What about just a new item entirely that inherits the Exporter simply called Regulator? Doesn't have to look any different, just provides the numerical controls that the old Regulator provided (potentially allowing any # entered as well, like if you wanted to stock exactly 200 Oak Wood in something you could enter 200. Use the tiny numbers shown in computer rather than the usual ItemStack ones). Similarly, in Fluid mode, show b values but allow typing in mb values directly when clicking an item in the list.

Clicking an item in the list brings up the "enter number" dialog thing. Shift-clicking would remove it.

**Comment by ProfessorBiddle** [comment]
> What about just a new item entirely that inherits the Exporter simply called Regulator? Doesn't have to look any different, just provides the numerical controls that the old Regulator provided (potentially allowing any # entered as well, like if you wanted to stock exactly 200 Oak Wood in something you could enter 200. Use the tiny numbers shown in computer rather than the usual ItemStack ones). 
> 

A little like the detector, but as an exporter would be cool, although this can be accomplished in a clunky fashion with a subnet w/ external storage and detector and exporter from main net.

**Comment by raoulvdberge** [comment]
Thx for all the input. Regulator mode has been re-added for the latest update as an upgrade in the exporter.
